print("Definitely not a Phishing Scam")
print()
myName = input("Your Name:\n")
print("Thanks for logging in")
print(myName)
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely wont put")
print(cardNumber)
print("into Amazon and order anything weird")
print()
print("Promise")
maidenName = input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that")
print(maidenName)
print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")

print("Getting to know you!")
name = input("What's your name? ")
favorite_food = input("What's your favorite food? ")
favorite_music = input("What's your favorite music? ")
location = input("Where do you live? ")
print("You are ",name)
print("You're probably hungry for ",favorite_food)
print("and you're definitely getting your groove on to", favorite_music)
print("living in the amazing",location)